### PR TITLE
Remove deprecation warning in node v7

### PR DESCRIPTION
**Pull request by maximkoretskiy**
See https://github.com/nodejs/node/issues/9346

### CODE REVIEW

**Comment by cthrax** [comment]
What is this correcting?

**Comment by maximkoretskiy** [comment]
If you try to use this plugin on node v7, U'll see deprecation warnings like it was described here https://github.com/nodejs/node/issues/9346.

**Comment by seglo** [comment]
@maximkoretskiy is the warning only made when using the plugin with Windows?  Do you mind pasting the warning output you're seeing?

**Comment by maximkoretskiy** [comment]
No, it's not connected with platform. Just opened PR to demonstrate what does it look.

https://travis-ci.org/seglo/connect-prism/jobs/218191578#L529

**Comment by maximkoretskiy** [comment]
@seglo ping

**Comment by seglo** [comment]
OK, we'll merge.  Thanks for the reproduction.

**Pull request merged**
